# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

- arguments:
  - "--cpp-define=MIN_VERSION_base(a,b,c)=1"
  - "-XQuasiQuotes"
  - "-XTemplateHaskell"
  - "--ignore-glob=hpgsql-tests/**"
  - "--ignore-glob=hpgsql-benchmarks/**"
  - "--ignore-glob=hpgsql-simple-compat/**"
  - "--ignore-glob=hpgsql-simple-compat-tests/**"
  - "--ignore-glob=hpgsql/src/Hpgsql/Networking.hs" # Mostly a copy from another library, best to keep similar to that

- ignore: {name: "Use camelCase", within: [ Hpgsql.TypeInfo ]}
- ignore: {name: "Avoid lambda"} # Preferred arity can be an important optimization
- ignore: {name: "Redundant lambda"} # Preferred arity can be an important optimization
- ignore: {name: "Collapse lambdas"} # Preferred arity can be an important optimization
- ignore: {name: "Replace case with maybe"}
- ignore: {name: "Use const"} # Unclear what happens to functions' preferred arity when using const
- ignore: {name: "Use for_"}
- ignore: {name: "Use list comprehension"}

- modules:
  - {name: Control.Exception, within: [], message: "Use Control.Exception.Safe instead"}

- functions:
  - {name: Prelude.foldl', within: [], message: "foldl' is only in the Prelude since GHC 9.8. Import it from Data.List instead."}
  - {name: Data.List.NonEmpty.fromList, within: [], message: "fromList is partial. Use nonEmpty from Data.List.NonEmpty instead."}
  - {name: "Data.List.NonEmpty.!!", within: [], message: "(!!) is partial. Use safe indexing instead."}
  - {name: "waitReadSocketSTM", within: [], message: "waitReadSocketSTM is not available in older versions of the network library. Use functions from our own Networking module instead."}
  
