# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash # Implies `set -eo pipefail`, among other things. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

env:
  CI: 1
  HPGSQL_THREADED: +threaded

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive

    - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # 31.3.30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters = https://cache.nixos.org https://mzabani.cachix.org https://cache.iog.io
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= mzabani.cachix.org-1:wnkKakfl+rbT7zTtV1P1tAtjBTuh6GQVX7LfSd9sMbA= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Build hpgsql
      run: nix-build --no-out-link -A hpgsql

    - name: Build hpgsql-tests
      run: nix-build --no-out-link -A hpgsql-tests

    - name: Build benchmarks
      run: nix-build --no-out-link -A hpgsql-benchmarks

    - name: Run tests
      run: |
        nix-env -iA concurrently -f ./nix/nixpkgs.nix
        # GHC's single and multi-threaded runtimes are different with respect
        # to many things, and our library relies on a lot of ThreadId tracking,
        # interruption safety, MVars and STM, so we test the single threaded
        # runtime, too.
        concurrently -g --timings --names pg18,pg17,pg16,pg15,pg14,single-threaded-rts,ghc984,ghc967 \
          'timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg18-tests.txt nix-build --no-out-link -A testsPg18' \
          'timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg17-tests.txt nix-build --no-out-link -A testsPg17' \
          'timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg16-tests.txt nix-build --no-out-link -A testsPg16' \
          'timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg15-tests.txt nix-build --no-out-link -A testsPg15' \
          'timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg14-tests.txt nix-build --no-out-link -A testsPg14' \
          'nix-build --no-out-link --argstr threading "-threaded" -A hpgsql-tests && timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg18-single-threaded-rts-tests.txt nix-build --no-out-link --argstr threading "-threaded" -A testsPg18' \
          'nix-build --no-out-link --argstr ghc ghc984 -A hpgsql-tests && timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg18-ghc984-tests.txt nix-build --no-out-link --argstr ghc ghc984 -A testsPg18' \
          'nix-build --no-out-link --argstr ghc ghc967 -A hpgsql-tests && timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg18-ghc967-tests.txt nix-build --no-out-link --argstr ghc ghc967 -A testsPg18'

    - name: Run hpgsql-simple-compat tests
      run: |
        scripts/ci/run-tests-and-annotate-with-error.sh local/hpgsql-simple-compat-tests.txt nix-build --no-out-link -A hpgsqlSimpleCompatTestsPg18

    - name: Run hlint
      run: nix-shell -p '(import ./nix/nixpkgs.nix {}).haskellPackages.hlint' --run 'hlint .'

  build-aarch64-darwin:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive

    - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # 31.3.30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          substituters = https://cache.nixos.org https://mzabani.cachix.org https://cache.iog.io
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= mzabani.cachix.org-1:wnkKakfl+rbT7zTtV1P1tAtjBTuh6GQVX7LfSd9sMbA= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Install basic software
      run: nix-env -iA coreutils -f ./nix/nixpkgs.nix # for the timeout CLI

    - name: List locales
      run: locale -a

    - name: Print some possibly useful limits
      run: |
        # According to https://doc.owncloud.com/server/next/admin_manual/troubleshooting/path_filename_length.html
        # Macs do have an undocumented limit of 1024 bytes for file paths.
        # If this is true, then it can explain some not-so-occasional test failures
        # we see for Mac. So we print this here, and a few other interesting limits.
        getconf NAME_MAX /
        getconf PATH_MAX /
        ulimit -n # Max number of open file descriptors

    - name: Build hpgsql
      run: nix-build --no-out-link -A hpgsql

    - name: Build hpgsql-tests
      run: nix-build --no-out-link -A hpgsql-tests

    - name: Run tests
      run: |
        # Postgres-version dependent tests for each possible version next
        # We test the last version with the vanilla nixpkgs-built derivation,
        # not the IOHK one. We assume differences in the codebase regarding different
        # postgres versions aren't enough to make it worth testing every version here too.
        # We don't run these concurrently because Nix does not have a sandbox in Macs, so it's
        # not worth the risk.
        timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg18-tests.txt nix-build --no-out-link -A testsPg18
        timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg17-tests.txt nix-build --no-out-link -A testsPg17
        timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg16-tests.txt nix-build --no-out-link -A testsPg16
        timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg15-tests.txt nix-build --no-out-link -A testsPg15
        timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg14-tests.txt nix-build --no-out-link -A testsPg14

    - name: Run tests with different combinations
      run: |
        # GHC's single and multi-threaded runtimes are different with respect
        # to many things, and our library relies on a lot of ThreadId tracking,
        # interruption safety, MVars and STM, so we test the single threaded
        # runtime, too.
        nix-build --no-out-link --argstr threading "-threaded" -A hpgsql-tests
        timeout 5m scripts/ci/run-tests-and-annotate-with-error.sh local/pg18-single-threaded-rts-tests.txt nix-build --no-out-link --argstr threading "-threaded" -A testsPg18

    - name: Run hpgsql-simple-compat tests
      run: |
        scripts/ci/run-tests-and-annotate-with-error.sh local/hpgsql-simple-compat-tests.txt nix-build --no-out-link -A hpgsqlSimpleCompatTestsPg18
